- name: demo on installing packages using loops
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: Install packages
    ansible.builtin.package:
      msg: "{{ item }}"
      state: present
    loop:
    - nginx
    - mysql
    - redis